formatter: markdown table
# header-from: ../docs/header.md
output:
  file: "./README.md"
  mode: replace
  template: |-
    # terraform-aws-acm

    Terraform module to create ACM Certificate
    ```
    module "acm" {
      source  = "Smartbrood/acm/aws"
      version = "1.0.0"
      route53_zone_name = "mydomain.org"
      subject_alternative_names = toset(["www.mydomain.org"])
    }
    ```

    {{ .Content }}

sections:
  hide-all: true
  show:
    - header
    - inputs
    - outputs
    - providers
    - resources

sort:
  enabled: true
  by: required