name: Terraform test

on:
  workflow_call:

env:
  TERRAFORM_VERSION: 1.7.1

jobs:
  deployment-to-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - name: Test terraform code
      run: |
      make test